# Generated by Django 4.0.4 on 2022-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(blank=True, max_length=70, null=True)),
                ('Answer', models.CharField(blank=True, max_length=100, null=True)),
                ('Option1', models.CharField(blank=True, max_length=50, null=True)),
                ('Option2', models.CharField(blank=True, max_length=50, null=True)),
                ('Option3', models.CharField(blank=True, max_length=50, null=True)),
                ('Option4', models.CharField(blank=True, max_length=50, null=True)),
                ('Marks', models.IntegerField(blank=True, max_length=50, null=True)),
                ('GetMarks', models.IntegerField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
