# Generated by Django 4.0.4 on 2022-06-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_answermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='Marks',
            new_name='Correct',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='Option1',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='Option2',
        ),
        migrations.RemoveField(
            model_name='answermodel',
            name='Question',
        ),
        migrations.AddField(
            model_name='answermodel',
            name='AtemptedQuestion',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='GetMarks',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='Wrong',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
