# Generated by Django 4.0.4 on 2022-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_rename_marks_answermodel_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='TotalNumber',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
