# Generated by Django 4.0.4 on 2022-06-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_answermodel_totalnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='AtemptedQuestion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='Correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='GetMarks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='TotalNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='Wrong',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
