# Generated by Django 4.0.4 on 2022-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_alter_answermodel_atemptedquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='Marks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
