# Generated by Django 4.0.4 on 2022-06-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_multiplechoicemodel_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleChoiceModel',
        ),
    ]
