# Generated by Django 4.0.4 on 2022-06-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_delete_singlechoicemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillintheblanksmodel',
            name='Option2',
        ),
    ]
