# Generated by Django 4.0.4 on 2022-06-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_remove_fillintheblanksmodel_option2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerModel',
        ),
    ]
