# Generated by Django 4.0.4 on 2022-06-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blogmodel_delete_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='Content',
            new_name='Body',
        ),
    ]
