# Generated by Django 4.0.4 on 2022-06-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='Video',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='Video_URL',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
