# Generated by Django 4.0.4 on 2022-06-10 19:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_blogmodel_video_blogmodel_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='Body',
            field=tinymce.models.HTMLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Video_URL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
