# Generated by Django 4.0.4 on 2022-06-11 09:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_alter_blogmodel_body_alter_blogmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='Body',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
