# Generated by Django 4.0.4 on 2022-06-11 11:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_alter_blogmodel_body_alter_blogmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='Body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
